feat: publish task
nervosnetwork/axon-prototype-2 pull request #25
Opened 2021-06-25 18:31 UTC by CQUPTYHM

2021-06-26 03:29 UTC, handsome0hell requested changes

2021-06-26 03:29 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || is_cell_count_smaller(PUB_TASK_OUTPUT_CELL_COUNT_MIN, Source::Output)
Please remove this condition, since it's value is already confirmed below.

2021-06-26 03:29 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    let sidechain_bond_lock_args_input = SidechainBondCellLockArgs::load(SIDECHAIN_BOND_INPUT)?;
There is a macro called `load_entities`, please use it to simplify your code.

2021-06-26 03:29 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_config_dep.admin_lock_arg != ADMIN_LOCK
Is admin lock args needed here? If admin can't publish tasks, please remove this. If he can, please correct this.

2021-06-26 03:29 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_state_input.committed_block_hash != sidechain_state_input.latest_block_hash
I think `ConfirmTasks` is the place to keep the hash <-> height consistency, not here.

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || sidechain_bond_lock_args_output.unlock_sidechain_height != task_cell_output.check_block_height_to
I guess `check_block_height_to` don't have to equal to `unlock_sidechain_height`

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || task_cell_data != task_cell_output
Please move some conditions out since most of them are not necessary to be repeat.

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/pattern.rs
> -
No meaningless modifications please.

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    if sidechain_state_type_args_input != sidechain_state_type_args_output
Please confirm that the transformation between input&ouput `sidechain_state`, make sure that only needed things are changed.

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_bond_lock_args_input.unlock_sidechain_height > sidechain_state_input.committed_block_height
Please make sure that the bond won't be unlocked until the end of these tasks.

2021-06-26 03:29 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_bond_input.amount < sidechain_config_dep.minimal_bond
Please check the consistency of `sidechain_bond lock args`

2021-06-26 03:39 UTC, handsome0hell commented on axon-ckb-contracts/common/src/lib.rs
> +    255, 48,
If there are always some people will get wrong result, leave it unchanged.

2021-06-26 04:31 UTC, CQUPTYHM commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || sidechain_bond_lock_args_output.unlock_sidechain_height != task_cell_output.check_block_height_to
unlock_sidechain_height <= input.SSC.commited_block_height就行

2021-06-26 04:34 UTC, CQUPTYHM commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || task_cell_data != task_cell_output
哪个条件不需要？

2021-06-26 04:35 UTC, CQUPTYHM commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    if sidechain_state_type_args_input != sidechain_state_type_args_output
sidechain_state_type_args_input 和 sidechain_state_type_args_output所有数据都要相等

2021-06-26 04:40 UTC, CQUPTYHM commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_bond_lock_args_input.unlock_sidechain_height > sidechain_state_input.committed_block_height
不是必须要解锁才能再 发布任务吗

2021-06-26 04:54 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || sidechain_bond_lock_args_output.unlock_sidechain_height != task_cell_output.check_block_height_to
No, if it is less than inputs committed height, then it's already unlockable now.

2021-06-26 04:55 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +            || task_cell_data != task_cell_output
Almost all, since they are already same as the first one.

2021-06-26 04:55 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    if sidechain_state_type_args_input != sidechain_state_type_args_output
Then what about cell data? Here we only checked type args.

2021-06-26 04:56 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_bond_lock_args_input.unlock_sidechain_height > sidechain_state_input.committed_block_height
Of course not. If the sidechain bond is unlockable, we have no way to avoid collector from being evil.

2021-06-26 16:32 UTC, handsome0hell requested changes

2021-06-26 16:32 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +const CODE_CELL_OUTPUT: CellOrigin = CellOrigin(0, Source::Output);
Please use existed constants `CODE_INPUT` `CODE_OUTPUT`

2021-06-26 16:32 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    let sidechain_bond_lock_args_dep = SidechainBondCellLockArgs::load(SIDECHAIN_BOND_DEP)?;
`load_entities` also works on dependencies.

2021-06-26 16:32 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    if sidechain_config_dep.challenge_threshold > sidechain_config_dep.checker_total_count
`challenge_threshold` is for challenge tasks. Maybe you mean `checker_threshold` here?

2021-06-26 16:32 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +    {
Please check the `chain_id` of the sidechain config here.

2021-06-26 16:32 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        || sidechain_state_input.committed_block_height != sidechain_state_output.committed_block_height
Compare *transformed* input with output directly. If we only compare part of these fields, adding more fields in the future might ruin these code.

2021-06-26 16:32 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_publish_task.rs
> +        let task_cell_type_args = TaskCellTypeArgs::load(CellOrigin(i.into(), Source::Output))?;
Please remove the unnecessary 'into()'.

2021-06-26 17:44 UTC, handsome0hell approved these changes
LGTM

2021-06-26 18:08 UTC, handsome0hell approved these changes
LGTM

2021-06-27 15:51 UTC, LycrusHamster approved these changes

2021-06-27 15:51 UTC, merged