feat: collator submit task
nervosnetwork/axon-prototype-2 pull request #26
Opened 2021-06-29 11:10 UTC by CQUPTYHM

2021-06-29 16:23 UTC, handsome0hell requested changes

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +            CodeCellData: CODE_OUTPUT,
Please check `MuseTokenCell` here

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +    sidechain_fee_res.amount = witness.fee + sidechain_fee_input.amount;
It seems that there's no reason not to use `+=` here.

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +        checker_info_res.unpaid_fee = checker_info_input.unpaid_fee + witness.fee_per_checker;
Same as above, maybe `+=` is more readable.

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +        || sidechain_config_dep.commit_threshold as u128 * witness.fee != witness.fee_per_checker
I don't think this is true. Maybe you mean `Head count * Fee per checker == Total fee`?

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +        || sidechain_config_dep.collator_lock_arg != signer
I think it's not necessary to be collator to submit tasks.

2021-06-29 16:23 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/collator_submit_task.rs
> +            && checker_info_type_args_output.chain_id != witness.chain_id
Some checks are unnecessary since we already compared output with res, please remove them.

2021-06-30 06:28 UTC, handsome0hell commented on axon-ckb-contracts/tests/src/test_collator_submit_task.rs
> +    );
Please remove your debugging things.

2021-06-30 06:45 UTC, handsome0hell approved these changes
LGTM

2021-07-02 05:31 UTC, LycrusHamster approved these changes
LGTM

2021-07-02 05:31 UTC, merged