feat: checker join sidechain
nervosnetwork/axon-prototype-2 pull request #58
Opened 2021-08-11 14:17 UTC by CQUPTYHM

2021-08-11 14:49 UTC, handsome0hell requested changes

2021-08-11 14:49 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/checker_join_sidechain.rs
> -        || checker_bond_input_lock_args.checker_lock_arg != signer
checker bond should have the same owner with code cell.

2021-08-11 14:49 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/checker_join_sidechain.rs
> +    if !is_same_input_output(3, 4) {
Under this situation, attackers can at least keep occupying others' cells (`CIC`, `SCC` etc.) because almost all of our scripts only verify the existence of `code cell`.

2021-08-11 14:52 UTC, handsome0hell requested changes

2021-08-11 14:52 UTC, handsome0hell commented on axon-ckb-contracts/contracts/code-cell/src/checker_join_sidechain.rs
> +
`checker info output` is not checked.

2021-08-11 15:43 UTC, handsome0hell requested changes

2021-08-11 15:43 UTC, Hanssen0 commented on axon-ckb-contracts/contracts/code-cell/src/checker_join_sidechain.rs
> -    // TODO: add checker to config checkers
`checker_normal_count` in `sidechain config` should also be maintained.

2021-08-11 15:50 UTC, handsome0hell approved these changes
LGTM

2021-08-12 14:12 UTC, LycrusHamster approved these changes
LGTM

2021-08-12 14:12 UTC, merged