feat: use molecule for sidechain regist.
nervosnetwork/axon-prototype-2 pull request #80
Opened 2021-09-13 02:49 UTC by CQUPTYHM

2021-09-13 13:00 UTC, handsome0hell requested changes

2021-09-13 13:00 UTC, handsome0hell commented on axon-client/axon-client-common/src/modules/models/cells/sidechain_regist.ts
> +import { Cell, OutPoint } from "@ckb-lumos/base";
This file's name is incorrect.

2021-09-15 05:54 UTC, handsome0hell approved these changes
LGTM

2021-09-15 07:00 UTC, LycrusHamster approved these changes

2021-09-15 07:00 UTC, merged